### PR TITLE
Added animationData attribute

### PR DESCRIPTION
**Pull request by DominicBoettger**
I added the animationData attribute to be able to input the json - data from a angular application or via javascript.

### CODE REVIEW

**Review by splitinfinities — APPROVED** [review]
Looks awesome! This is super helpful. Good work!!

**Comment by splitinfinities** [comment]
I'll have this released shortly!

**Comment by splitinfinities** [comment]
Out in v1.1.0

**Comment by DominicBoettger** [comment]
👍

**Pull request merged**
